spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
